spring.application.name=dutydesk

# Render/Cloud: PORT env varsa onu istifadə et, lokalda 8080
server.port=${PORT:8080}

# Datasource: Render env-ləri ilə override oluna bilər
spring.datasource.url=${SPRING_DATASOURCE_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/dutydesk}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:123456}}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.session.jdbc.initialize-schema=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

spring.jpa.open-in-view=false

logging.level.root=info
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

app.security.jwt.secret=${JWT_SECRET:bXlfc2VjcmV0X2tleV9mb3JfaHNzNTYyX2VuY29kaW5nX3Nob3VsZF9iZV9hdF9sZWFzdF82NF9ieXRlc19sb25nX2FuZF9iYXNlNjRfZW5jb2RlZA==}
app.security.jwt.expiration-ms=86400000
app.security.reset-code.expiration-seconds=120
app.security.reset-token.expiration-ms=900000

springdoc.pathsToMatch=/api/**
